[package]
name = "servicelens"
version = "0.2.0"
edition = "2021"

[dependencies]
tauri = { version = "^2.0", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "^2.0", features = [] }
